### ISSUE TITLE
X & Y-axis stepper driver board resistive setup

### ISSUE THREAD

**Issue by JosselinCLEMENT** [BCN3D/BCN3DSigma-Electronics#3]
Hi Team,

Could you please let me know what are the original resistive setup of the X & Y stepper driver boards?

I tested the X axis resistivity and it was about 5 kOhm (ground to phase):

![stepper board](https://user-images.githubusercontent.com/32385070/31006940-17030918-a4ff-11e7-9003-557802e5b47a.jpg)

I am facing big issues with Y-axis shifting and I think that is mainly due to the Y-axis stepper board resistance setup. 

Could you please update me?

Thank you very much for your support.

Joss

**Comment by WanaGo** [comment]
Is this helpful?
[Driver-voltage.pdf](https://github.com/BCN3D/BCN3DSigma-Electronics/files/1384472/Driver-voltage.pdf)

**Comment by JosselinCLEMENT** [comment]
Hi WanaGo,

Thank you very much for your support! It works :+1: !
